name: Frontend CI/CD

on:
  push:
    branches: ["main"]
    paths:
      - "frontend/**"
      - "infra/**"
      - ".github/workflows/frontend-ci-cd.yml"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./infra/cicd/github-actions/frontend/build-deploy.yml
    with:
      build_dir: "frontend"
      environment: "dev"
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN_DEV }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      FRONTEND_BUCKET_NAME: ${{ secrets.FRONTEND_BUCKET_NAME }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
